# **4 TO - DO - Task**

Please complete all the problem listed below.

## **4.1 Exercise on Functions:**

**Task - 1:**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

In [ ]:
# Ask the user which type of conversion they want to perform
conversion_type = input("Choose conversion type (length, weight, volume): ")

Choose conversion type (length, weight, volume): length


What this does:

input() shows the message to the user

whatever the user types is stored in conversion_type

Example:

if user types length, then conversion_type will store "length"

2. Ask the user to input the value to be converted.

In [ ]:
# Ask the user to enter the value that needs to be converted
value = input("Enter the value to convert: ")

Enter the value to convert: 2


Explanation

input() displays a message to the user.

The user types a number.

The value is stored in the variable value.



3. Perform the conversion and display the result.

In [ ]:
# Convert the input value into a number so we can calculate
value = float(value)

# Perform conversion depending on the type selected
if conversion_type == "length":
    result = value * 3.28084   # convert meters to feet
    print("Converted value:", result, "feet")

elif conversion_type == "weight":
    result = value * 2.20462   # convert kilograms to pounds
    print("Converted value:", result, "pounds")

elif conversion_type == "volume":
    result = value * 0.264172  # convert liters to gallons
    print("Converted value:", result, "gallons")

else:
    print("Invalid conversion type selected.")

Converted value: 6.56168 feet


Explanation

float(value) converts the text input into a number so calculations can be done.

if checks which conversion the user selected.

Each conversion uses a conversion formula:

meters → feet (× 3.28084)

kilograms → pounds (× 2.20462)

liters → gallons (× 0.264172)

print() displays the converted result.

4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
try:
    # Convert the user input into a number
    value = float(value)

    # Perform conversion depending on the type selected
    if conversion_type == "length":
        result = value * 3.28084   # meters to feet
        print("Converted value:", result, "feet")

    elif conversion_type == "weight":
        result = value * 2.20462   # kilograms to pounds
        print("Converted value:", result, "pounds")

    elif conversion_type == "volume":
        result = value * 0.264172  # liters to gallons
        print("Converted value:", result, "gallons")

    else:
        # If user entered unsupported conversion type
        print("Unsupported conversion type.")

except ValueError:
    # This runs if the user enters something that is not a number
    print("Invalid input! Please enter a numeric value.")

Converted value: 6.56168 feet


Explanation

try:

This block tries to run the code.

value = float(value)

Converts user input to a number.

If the user types "abc" → it causes an error.

except ValueError:

Catches the error.

Prevents the program from crashing.

Shows a friendly message.

# **Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.



*   • The Program should:



1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).

In [ ]:
# Ask the user which mathematical operation they want to perform
operation = input("Choose an operation (sum, average, maximum, minimum): ")

Choose an operation (sum, average, maximum, minimum): sum


Explanation

input() asks the user to type something.

The user's choice is stored in the variable operation.

2. Ask the user to input a list of numbers (separated by spaces).

In [ ]:
# Ask the user to enter numbers separated by spaces
numbers_input = input("Enter numbers separated by spaces: ")

Enter numbers separated by spaces: 5 10 15 20


Explanation

input() asks the user to type several numbers.

The numbers should be separated by spaces.

The whole input is stored in the variable numbers_input.

3. Perform the selected operation and display the result.



In [ ]:
# Check which operation the user selected and perform it

if operation == "sum":
    result = sum(numbers)  # add all numbers in the list
    print("Sum:", result)

elif operation == "average":
    result = sum(numbers) / len(numbers)  # average = total / number of values
    print("Average:", result)

elif operation == "maximum":
    result = max(numbers)  # find the largest number
    print("Maximum:", result)

elif operation == "minimum":
    result = min(numbers)  # find the smallest number
    print("Minimum:", result)

else:
    print("Invalid operation selected.")

Sum: 50.0


Simple explanation

if operation == "sum"

Checks if the user chose sum.

sum(numbers)

Adds all numbers in the list.

Example:

numbers = [5, 10, 15]
Sum = 30

sum(numbers) / len(numbers)

Finds the average.

Example:

numbers = [5, 10, 15]

sum = 30
len = 3

average = 30 / 3 = 10

max(numbers)

Finds the largest number in the list.

Example:

[4, 8, 2] → 8

min(numbers)

Finds the smallest number in the list.

Example:

[4, 8, 2] → 2

Example run:

Choose operation: sum
Enter numbers separated by spaces: 5 10 15

Sum: 30

4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
try:
    # Convert input into a list of numbers
    numbers = [float(num) for num in numbers_input.split()]

    # Check if the list is empty
    if len(numbers) == 0:
        print("Error: The list is empty. Please enter some numbers.")

except ValueError:
    # This runs if the user enters something that is not a number
    print("Error: Invalid input! Please enter only numbers.")

Simple explanation

numbers_input.split()

Splits the text into pieces using spaces.

Example:

"5 10 15 20"

becomes:

["5", "10", "15", "20"]

[float(num) for num in numbers]

Converts each text number into a real number.

Example:

["5", "10", "15", "20"]

becomes

[5.0, 10.0, 15.0, 20.0]

try - except

Prevents the program from crashing if the user enters something like:

5 10 abc 20

Instead it prints:

Invalid input! Please enter only numbers.

# **4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

*   Requirements:

    – Define a function extract every other(lst) that takes a list lst as input and returns a
    new list containing every other element from the original list.
    
    – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from the list starting from the first element.
    """

    # Take every second element
    result = lst[::2]

    return result


numbers = [1, 2, 3, 4, 5, 6]

# Call the function and print the result
print(extract_every_other(numbers))

[1, 3, 5]


Simple Explanation
Function definition
def extract_every_other(lst):



*   Creates a function named extract_every_other
*   lst is the list given by the user.





Slicing
lst[::2]

This means:

    start : end : step

    start = beginning of list

    end = end of list

    step = 2 → take every second element

Example list:

[1, 2, 3, 4, 5, 6]

Indexes:

0 1 2 3 4 5

Taking step 2:

1, 3, 5
Example Usage
numbers = [1, 2, 3, 4, 5, 6]

result = extract_every_other(numbers)

print(result)

Output:

[1, 3, 5]

**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.



*   • Requirements:

    – Define a function get sublist(lst, start, end) that takes a list lst, a starting index
    start, and an ending index end as input and returns the sublist from start to end (inclusive).
    
    – Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
    be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Return a sublist from the given list between the start and end indices (inclusive).

    Parameters:
        lst (list): The original list.
        start (int): Starting index.
        end (int): Ending index.

    Returns:
        list: A sublist from start to end.
    """

    # Get elements from start to end
    sublist = lst[start:end + 1]

    return sublist


# Example list
numbers = [1, 2, 3, 4, 5, 6]

# Call the function
result = get_sublist(numbers, 2, 4)

# Print the result
print("Sublist:", result)

Sublist: [3, 4, 5]


Simple Explanation
Function definition
def get_sublist(lst, start, end):

>Creates a function called get_sublist

>lst → the list

-start → starting position

-end → ending position

Slicing

lst[start:end + 1]

Python slicing format:

list[start:end]

But end is normally excluded, so we add +1.

Example list:

[1, 2, 3, 4, 5, 6]

Indexes:

0 1 2 3 4 5

If:

start = 2
end = 4

Then:

lst[2:5]

Result:

[3, 4, 5]
Example Usage
numbers = [1, 2, 3, 4, 5, 6]

result = get_sublist(numbers, 2, 4)

print(result)

Output:

[3, 4, 5]

**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.


*   Requirements:

    – Define a function reverse list(lst) that takes a list lst and returns a reversed list using
    slicing.

    – Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].





In [ ]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
        lst (list): The original list.

    Returns:
        list: The reversed list.
    """

    # Reverse the list using slicing
    reversed_lst = lst[::-1]

    return reversed_lst


# Example list
numbers = [1, 2, 3, 4, 5]

# Call the function and store result
result = reverse_list(numbers)

# Print the result
print("Reversed list:", result)

Reversed list: [5, 4, 3, 2, 1]


Simple Explanation
Function definition
def reverse_list(lst):

>Creates a function called reverse_list

>lst is the list given to the function.

Slicing to reverse
lst[::-1]

Slicing format:

[start : end : step]

Here:

start → default (beginning)

end → default (end)

step → -1 means move backwards

So Python reads the list from end to start.

Example

Original list:

[1, 2, 3, 4, 5]

Reversed:

[5, 4, 3, 2, 1]
Example Usage
numbers = [1, 2, 3, 4, 5]

result = reverse_list(numbers)

print(result)

Output:

[5, 4, 3, 2, 1]

**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.


*  Requirements:

    – Define a function remove first last(lst) that takes a list lst and returns a sublist without
    the first and last elements using slicing.

    – Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4]



In [ ]:
def remove_first_last(lst):
    """
    Remove the first and last elements of a list.

    Parameters:
        lst (list): The original list.

    Returns:
        list: A new list without the first and last elements.
    """

    # Remove the first and last elements using slicing
    result = lst[1:-1]

    return result


# Example list
numbers = [1, 2, 3, 4, 5]

# Call the function
result = remove_first_last(numbers)

# Print the result
print("List without first and last elements:", result)

List without first and last elements: [2, 3, 4]


Simple Explanation
Function definition
def remove_first_last(lst):

Creates a function called remove_first_last

lst is the list provided to the function.

Slicing
lst[1:-1]

Slicing format:

list[start : end]

Here:

1 → start from the second element

-1 → stop before the last element

So it removes:

the first element

the last element

Example

Original list:

[1, 2, 3, 4, 5]

Indexes:

0 1 2 3 4

Using:

lst[1:-1]

Result:

[2, 3, 4]

Example Usage
numbers = [1, 2, 3, 4, 5]

result = remove_first_last(numbers)

print(result)

Output:

[2, 3, 4]

**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.



*  Requirements:

    – Define a function get first n(lst, n) that takes a list lst and an integer n as input and
    returns the first n elements of the list using slicing.
    
    – Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].



In [ ]:
def get_first_n(lst, n):
    """
    Return the first n elements of a list.

    Parameters:
        lst (list): The original list.
        n (int): Number of elements to extract.

    Returns:
        list: A list containing the first n elements.
    """

    # Take the first n elements using slicing
    result = lst[:n]

    return result


# Example list
numbers = [1, 2, 3, 4, 5]

# Call the function
result = get_first_n(numbers, 3)

# Print the result
print("First n elements:", result)

First n elements: [1, 2, 3]


Simple Explanation
Function definition
def get_first_n(lst, n):

Creates a function called get_first_n

lst → the list

n → number of elements we want

Slicing
lst[:n]

Slicing format:

list[start:end]

Here:

start → beginning of the list

end → n

So it takes the first n elements.

Example

List:

[1, 2, 3, 4, 5]

If:

n = 3

Then:

lst[:3]

Result:

[1, 2, 3]
Example Usage
numbers = [1, 2, 3, 4, 5]

result = get_first_n(numbers, 3)

print(result)

Output:

[1, 2, 3]

**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.



*   Requirements:

    – Define a function get last n(lst, n) that takes a list lst and an integer n as input and
    returns the last n elements of the list.
    
    – Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].


In [ ]:
def get_last_n(lst, n):
    """
    Return the last n elements of a list.

    Parameters:
        lst (list): The original list.
        n (int): Number of elements to extract from the end.

    Returns:
        list: A list containing the last n elements.
    """

    # Take the last n elements using slicing
    result = lst[-n:]

    return result


# Example list
numbers = [1, 2, 3, 4, 5]

# Call the function
result = get_last_n(numbers, 2)

# Print the result
print("Last n elements:", result)

Last n elements: [4, 5]


Simple Explanation
Function definition
def get_last_n(lst, n):

Creates a function called get_last_n

lst → the list

n → number of elements to take from the end

Slicing
lst[-n:]

Slicing format:

list[start:end]

Here:

-n → start n positions from the end

: → go until the end of the list

Example

List:

[1, 2, 3, 4, 5]

If:

n = 2

Then:

lst[-2:]

Result:

[4, 5]
Example Usage
numbers = [1, 2, 3, 4, 5]

result = get_last_n(numbers, 2)

print(result)

Output

[4, 5]



**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.



*   Requirements:

    – Define a function reverse skip(lst) that takes a list lst and returns a new list containing
    every second element starting from the second-to-last, moving backward.
    
    – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].



In [ ]:
def reverse_skip(lst):
    """
    Return elements in reverse order starting from the second-to-last element,
    skipping one element each time.

    Parameters:
        lst (list): The original list.

    Returns:
        list: A list containing every second element in reverse order.
    """

    # Start from second-to-last element and move backwards skipping one element
    result = lst[-2::-2]

    return result


# Example list
numbers = [1, 2, 3, 4, 5, 6]

# Call the function
result = reverse_skip(numbers)

# Print the result
print("Reverse skip:", result)


Reverse skip: [5, 3, 1]


# **4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.


*   Requirements:

    – Define a function flatten(lst) that takes a nested list lst and returns a flattened version
    of the list.

    – Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].



In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single list.

    Parameters:
        lst (list): A nested list.

    Returns:
        list: A flattened list containing all elements.
    """

    flat_list = []

    # Go through each sublist
    for sublist in lst:
        # Go through each element inside the sublist
        for item in sublist:
            flat_list.append(item)

    return flat_list


# Ask the user to enter nested lists
user_input = input("Enter nested lists (example: [[1,2],[3,4],[5]]): ")

# Convert input text into a real Python list
nested_list = eval(user_input)

# Call the function
result = flatten(nested_list)

# Print the result
print("Flattened list:", result)

Enter nested lists (example: [[1,2],[3,4],[5]]): [[1,2],[3,4],[5]]
Flattened list: [1, 2, 3, 4, 5]


Simple Explanation

User input

    [[1,2],[3,4],[5]]

This is a nested list.

Loop through sublists

    for sublist in lst:

Example:

[1,2]
[3,4]
[5]

Loop through elements

    for item in sublist:

This extracts each number.

Append items

    flat_list.append(item)

Final result:

[1,2,3,4,5]

**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.



*   Requirements:

    – Define a function access nested element(lst, indices) that takes a nested list lst and
    a list of indices indices, and returns the element at that position.
    
    – Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
    2], the output should be 6.



In [ ]:
def access_nested_element(lst, indices):
    """
    Access an element from a nested list using given indices.

    Parameters:
        lst (list): The nested list.
        indices (list): The position of the element [row, column].

    Returns:
        element: The element found at the given position.
    """

    # Access the element using the indices
    element = lst[indices[0]][indices[1]]

    return element


# Ask the user to enter a nested list
user_list = input("Enter a nested list (example: [[1,2,3],[4,5,6],[7,8,9]]): ")

# Convert input string into a Python list
nested_list = eval(user_list)

# Ask the user for indices
user_indices = input("Enter indices as [row,column] (example: [1,2]): ")

# Convert input into list
indices = eval(user_indices)

# Call the function
result = access_nested_element(nested_list, indices)

# Print the result
print("Element at the given indices:", result)

Enter a nested list (example: [[1,2,3],[4,5,6],[7,8,9]]):  [[1,2,3],[4,5,6],[7,8,9]]
Enter indices as [row,column] (example: [1,2]): [1,2]
Element at the given indices: 6


Simple Explanation

Nested list:

[[1,2,3],

 [4,5,6],

 [7,8,9]]

Indexes:

row 0 → [1,2,3]

row 1 → [4,5,6]

row 2 → [7,8,9]

Accessing:

lst[1][2]

means:

row 1 → [4,5,6]

column 2 → 6

Result:

6

**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).



*   Requirements:

    – Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
    the elements.
    
    – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.



In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list.

    Parameters:
        lst (list): A nested list containing numbers.

    Returns:
        int/float: The total sum of all elements.
    """

    total = 0

    for item in lst:
        # If the item is a list, call the function again (recursion)
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total


# Ask the user to enter a nested list
user_input = input("Enter a nested list (example: [[1,2],[3,[4,5]],6]): ")

# Convert the input string to a Python list
nested_list = eval(user_input)

# Call the function
result = sum_nested(nested_list)

# Print the result
print("Sum of all elements:", result)

Enter a nested list (example: [[1,2],[3,[4,5]],6]): [[1,2],[3,[4,5]],6]
Sum of all elements: 21


Simple Explanation

Example list:

[[1,2],[3,[4,5]],6]

Numbers inside:

1 + 2 + 3 + 4 + 5 + 6

Result:

21

Important Part
if
    
    isinstance(item, list):

This checks if the item is another list.

If it is, the function calls itself again to go deeper into the list.

This is called recursion, which allows the function to work no matter how deep the nested list is.

**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.
*   Requirements:

    – Define a function remove element(lst, elem) that removes elem from lst and returns the
    modified list.

    – Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
    be [[1], [3], [4, 5]].





In [ ]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): A nested list.
        elem: The element to remove.

    Returns:
        list: Modified nested list without the element.
    """

    new_list = []

    for item in lst:
        # If the item is a list, apply the function recursively
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        else:
            # Only add the item if it is not equal to elem
            if item != elem:
                new_list.append(item)

    return new_list


# Ask the user to enter a nested list
user_list = input("Enter a nested list (example: [[1,2],[3,2],[4,5]]): ")

# Convert input to Python list
nested_list = eval(user_list)

# Ask the user which element to remove
element = int(input("Enter the element to remove: "))

# Call the function
result = remove_element(nested_list, element)

# Print the result
print("List after removing element:", result)

Enter a nested list (example: [[1,2],[3,2],[4,5]]): [[1,2],[3,2],[4,5]]
Enter the element to remove: 5
List after removing element: [[1, 2], [3, 2], [4]]


Simple Explanation

Original list:

[[1,2],[3,2],[4,5]]

Remove 2.

Result:

[[1],[3],[4,5]]

Important line

    if isinstance(item, list):

This checks if the element is another list.
If yes, the function calls itself again to remove the element inside that list.

**5. Find the Maximum Element in a Nested List:**





Write a Python function that finds the maximum element in a nested list (regardless of depth).
*   Requirements:

    – Define a function find max(lst) that takes a nested list lst and returns the maximum
    element.

    – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
        lst (list): A nested list containing numbers.

    Returns:
        int/float: The maximum element found in the list.
    """

    max_value = float('-inf')  # start with a very small number

    for item in lst:
        # If the item is a list, search inside it
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        # Update the maximum value
        if value > max_value:
            max_value = value

    return max_value


# Ask the user to enter a nested list
user_input = input("Enter a nested list (example: [[1,2],[3,[4,5]],6]): ")

# Convert input string into a Python list
nested_list = eval(user_input)

# Call the function
result = find_max(nested_list)

# Print the result
print("Maximum element:", result)

Enter a nested list (example: [[1,2],[3,[4,5]],6]): [[1,2],[3,[4,5]],6]
Maximum element: 6


Simple Explanation

Example nested list:

[[1,2],[3,[4,5]],6]

Numbers inside:

1, 2, 3, 4, 5, 6

The largest number is:

6

Important part

    if isinstance(item, list):

This checks if the item is another list.
If it is, the function calls itself again to search deeper.

**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

* Requirements:

    – Define a function count occurrences(lst, elem) that counts the occurrences of elem in
    the nested list lst.

    – Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
    be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
        lst (list): A nested list.
        elem: The element to count.

    Returns:
        int: Number of times elem appears in the list.
    """

    count = 0

    for item in lst:
        # If the item is another list, search inside it
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1

    return count


# Ask the user to enter a nested list
user_list = input("Enter a nested list (example: [[1,2],[2,3],[2,4]]): ")

# Convert input text to a Python list
nested_list = eval(user_list)

# Ask the user which element to count
element = int(input("Enter the element to count: "))

# Call the function
result = count_occurrences(nested_list, element)

# Print the result
print("Number of occurrences:", result)

Enter a nested list (example: [[1,2],[2,3],[2,4]]): [[1,2],[2,3],[2,4]]
Enter the element to count: 2
Number of occurrences: 3


Simple Explanation

Nested list:

[[1,2],[2,3],[2,4]]

Looking for 2.

Numbers:

1,2,
2,3,
2,4

Occurrences of 2:

3 times

Important Part

    if isinstance(item, list):

This checks if the item is another list.

If yes, the function calls itself again to count elements inside that list.

This allows it to work for lists nested at any depth.

**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

* Requirements:

    – Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
    flattened list.

    – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
    [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
        lst (list): A deeply nested list.

    Returns:
        list: A flattened list containing all elements.
    """

    flat_list = []

    for item in lst:
        # If the item is another list, flatten it recursively
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)

    return flat_list


# Ask the user to enter a deeply nested list
user_input = input("Enter a nested list (example: [[[1,2],[3,4]],[[5,6],[7,8]]]): ")

# Convert input string to Python list
nested_list = eval(user_input)

# Call the function
result = deep_flatten(nested_list)

# Print the result
print("Flattened list:", result)

Enter a nested list (example: [[[1,2],[3,4]],[[5,6],[7,8]]]): [[[1,2],[3,4]],[[5,6],[7,8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


Simple Explanation

Example list:

[[[1,2],[3,4]],[[5,6],[7,8]]]

Numbers inside:

1,2,3,4,5,6,7,8

Final flattened list:

[1,2,3,4,5,6,7,8]

Important Line

    flat_list.extend(deep_flatten(item))

extend() adds multiple elements to the list

deep_flatten(item) calls the function again to flatten deeper lists

This allows the function to work no matter how deep the nested list is.

**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

* Requirements:

    – Define a function average nested(lst) that takes a nested list lst and returns the average
    of all the elements.

    – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Calculate the average of all numbers in a nested list.

    Parameters:
        lst (list): A nested list containing numbers.

    Returns:
        float: The average of all elements.
    """

    total = 0
    count = 0

    for item in lst:
        # If item is another list, process it recursively
        if isinstance(item, list):
            sub_total, sub_count = average_nested_helper(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1

    return total / count


def average_nested_helper(lst):
    """
    Helper function to calculate total and count of nested list elements.
    """

    total = 0
    count = 0

    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested_helper(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1

    return total, count


# Ask the user to enter a nested list
user_input = input("Enter a nested list (example: [[1,2],[3,4],[5,6]]): ")

# Convert the input string into a Python list
nested_list = eval(user_input)

# Call the function
result = average_nested(nested_list)

# Print the result
print("Average of all elements:", result)

Enter a nested list (example: [[1,2],[3,4],[5,6]]): [[1,2],[3,4],[5,6]]
Average of all elements: 3.5


Simple Explanation

Example list:

[[1,2],[3,4],[5,6]]

Numbers:

1,2,3,4,5,6

Total:

1+2+3+4+5+6 = 21

Count:

6 numbers

Average:

21 ÷ 6 = 3.5

# **10 To - Do - NumPy**

# **10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np  # import numpy library to work with arrays

# create an empty 2x2 array using numpy
# np.empty((2,2)) creates an array with 2 rows and 2 columns
# the values inside are random/uninitialized because numpy only allocates memory
array_empty = np.empty((2,2))

# print the result so the user can see the array
print("Empty 2x2 array:")
print(array_empty)

Empty 2x2 array:
[[5.32440399e-315 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]


np.empty() does NOT fill with zeros.
It only allocates memory, so the values may look random.

2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np  # import numpy library to work with numerical arrays

# ask the user to confirm creation of the array (simple user interaction)
user_input = input("Press Enter to create a 4x2 array filled with ones: ")

# create an array with 4 rows and 2 columns filled with ones
# np.ones((4,2)) means create a matrix of size 4x2 where every value = 1
ones_array = np.ones((4,2))

# print the array so the user can see the result
print("Array of ones with shape 4x2:")
print(ones_array)

Press Enter to create a 4x2 array filled with ones: 
Array of ones with shape 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np  # import numpy library to work with arrays

# ask the user to enter number of rows
rows = int(input("Enter number of rows: "))  # convert input to integer

# ask the user to enter number of columns
cols = int(input("Enter number of columns: "))  # convert input to integer

# ask the user what value should fill the array
value = int(input("Enter the value to fill the array with: "))  # this value will fill every cell

# create an array using np.full()
# np.full((rows, cols), value) creates a matrix with given shape
# every element inside the array will be the value entered by the user
full_array = np.full((rows, cols), value)

# print the array so the user can see the result
print("Array filled with the given value:")
print(full_array)

Enter number of rows: 4
Enter number of columns: 4
Enter the value to fill the array with: 9
Array filled with the given value:
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np  # import numpy library

# ask the user to enter numbers separated by spaces
user_input = input("Enter numbers separated by spaces (example: 1 2 3 4): ")

# convert the input string into a list of integers
numbers = [int(x) for x in user_input.split()]  # split separates numbers by space

# convert the list into a numpy array
original_array = np.array(numbers)  # np.array() converts Python list to NumPy array

# create a new array of zeros with the same shape as the original array
zeros_array = np.zeros_like(original_array)  # same shape and type but filled with 0

# print the original array
print("Original array:")
print(original_array)

# print the new zero array
print("Zero array with same shape:")
print(zeros_array)

Enter numbers separated by spaces (example: 1 2 3 4): 2 4 6 8
Original array:
[2 4 6 8]
Zero array with same shape:
[0 0 0 0]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np  # import numpy library

# ask the user to enter numbers separated by spaces
user_input = input("Enter numbers separated by spaces (example: 2 4 6 8): ")

# convert the input string into a list of integers
numbers = [int(x) for x in user_input.split()]  # split separates the values and int() converts them to integers

# convert the list into a numpy array
original_array = np.array(numbers)  # np.array() converts the Python list into a NumPy array

# create a new array of ones with the same shape and type as the original array
ones_array = np.ones_like(original_array)  # np.ones_like() copies the shape but fills it with 1s

# print the original array
print("Original array:")
print(original_array)

# print the new array of ones
print("Ones array with same shape:")
print(ones_array)

Enter numbers separated by spaces (example: 2 4 6 8): 1 3 5 7 9
Original array:
[1 3 5 7 9]
Ones array with same shape:
[1 1 1 1 1]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np  # import numpy library so we can work with NumPy arrays

# ask the user to enter numbers separated by spaces
user_input = input("Enter numbers separated by spaces (example: 1 2 3 4): ")

# convert the input string into a Python list of integers
# split() separates the numbers and int() converts them from text to integers
new_list = [int(x) for x in user_input.split()]

# convert the Python list into a NumPy array
numpy_array = np.array(new_list)  # np.array() converts a normal Python list into a NumPy array

# print the original Python list
print("Python list:")
print(new_list)

# print the NumPy array
print("Converted NumPy array:")
print(numpy_array)

Enter numbers separated by spaces (example: 1 2 3 4): 1 2 3 6
Python list:
[1, 2, 3, 6]
Converted NumPy array:
[1 2 3 6]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np  # import numpy library for array operations

# create an array starting from 10 and ending at 49
# np.arange(10, 50) starts at 10 and stops before 50
array_range = np.arange(10, 50)

# print the array so the user can see the output
print("Array from 10 to 49:")
print(array_range)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np  # import numpy library for array operations

# create an array with numbers from 0 to 8
# np.arange(0,9) generates numbers starting from 0 and stopping before 9
array_numbers = np.arange(0, 9)

# reshape the array into a 3x3 matrix
# reshape(3,3) changes the shape of the array into 3 rows and 3 columns
matrix_3x3 = array_numbers.reshape(3, 3)

# print the matrix so the user can see the result
print("3x3 matrix with values from 0 to 8:")
print(matrix_3x3)

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np  # import numpy library to work with arrays

# create a 3x3 identity matrix
# np.eye(3) creates a square matrix with 1s on the diagonal and 0s elsewhere
identity_matrix = np.eye(3)

# print the identity matrix so the user can see the result
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np  # import numpy library to work with arrays

# create a random array with 30 elements
# np.random.random(30) generates 30 random numbers between 0 and 1
random_array = np.random.random(30)

# calculate the mean (average) of the array
# .mean() adds all values and divides by the total number of elements
mean_value = random_array.mean()

# print the random array
print("Random array of size 30:")
print(random_array)

# print the mean of the array
print("Mean of the array:", mean_value)

Random array of size 30:
[0.20551244 0.33557511 0.63486689 0.44637251 0.77694754 0.57288017
 0.97530778 0.02926219 0.43448052 0.13899596 0.49367153 0.93624614
 0.45783173 0.21574715 0.06951405 0.87296788 0.45123357 0.78801087
 0.67701756 0.93283996 0.07381237 0.9308489  0.57513645 0.37841727
 0.66859532 0.2062422  0.54760975 0.80319335 0.76519171 0.19460889]
Mean of the array: 0.5196312587385759


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np  # import numpy library to work with arrays

# create a 10x10 array filled with random numbers between 0 and 1
# np.random.random((10,10)) generates a matrix with 10 rows and 10 columns
random_matrix = np.random.random((10,10))

# find the minimum value in the array
# .min() checks all elements and returns the smallest value
min_value = random_matrix.min()

# find the maximum value in the array
# .max() checks all elements and returns the largest value
max_value = random_matrix.max()

# print the random matrix
print("10x10 Random Matrix:")
print(random_matrix)

# print the minimum value
print("Minimum value in the matrix:", min_value)

# print the maximum value
print("Maximum value in the matrix:", max_value)

10x10 Random Matrix:
[[0.47190326 0.06691196 0.48431383 0.85645355 0.00238086 0.48378777
  0.52095352 0.35271939 0.72180019 0.11800338]
 [0.39557625 0.86081666 0.68466597 0.79306466 0.33515264 0.95992055
  0.20367349 0.77459441 0.83849929 0.34813243]
 [0.81497971 0.62640714 0.79837265 0.50078562 0.56136716 0.0621362
  0.25167823 0.99596415 0.18581235 0.03381139]
 [0.1232014  0.79619021 0.445867   0.4051001  0.18062074 0.09598782
  0.00480463 0.54025486 0.21659822 0.45958983]
 [0.27946603 0.94022648 0.76587061 0.26457462 0.09156456 0.44375708
  0.67094846 0.43560721 0.43784785 0.67404339]
 [0.61519033 0.74410188 0.27289667 0.11501696 0.57289706 0.93384939
  0.75264347 0.61869198 0.53294018 0.94717163]
 [0.13738836 0.92337128 0.03571521 0.77229574 0.03606911 0.83297759
  0.53510317 0.85453666 0.16944289 0.86105018]
 [0.52195572 0.66185243 0.91687522 0.05298607 0.28452324 0.48191877
  0.68730549 0.25044547 0.71584487 0.081704  ]
 [0.50052933 0.8027445  0.20553263 0.28188463 0.06132528 0.6

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np  # import numpy library

# create an array of size 10 filled with zeros
# np.zeros(10) creates a 1D array with 10 elements, all initialized to 0
zero_array = np.zeros(10)

# replace the 5th element with 1
# indexing in Python starts from 0, so the 5th element is index 4
zero_array[4] = 1

# print the resulting array
print("Array after replacing the 5th element with 1:")
print(zero_array)

Array after replacing the 5th element with 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np  # import numpy library

# ask the user to enter numbers separated by spaces
user_input = input("Enter numbers separated by spaces (example: 1 2 0 0 4 0): ")

# convert the input string into a list of integers
# split() separates the numbers and int() converts them from text to integers
arr_list = [int(x) for x in user_input.split()]

# convert the list into a numpy array
arr = np.array(arr_list)  # np.array() converts Python list to NumPy array

# reverse the array using slicing
# [::-1] means start from the end and move backwards
reversed_array = arr[::-1]

# print the original array
print("Original array:")
print(arr)

# print the reversed array
print("Reversed array:")
print(reversed_array)

Enter numbers separated by spaces (example: 1 2 0 0 4 0): 1 2 0 0 0 0
Original array:
[1 2 0 0 0 0]
Reversed array:
[0 0 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np  # import numpy library

# ask the user to enter the size of the square matrix
size = int(input("Enter the size of the matrix (example 5 for a 5x5 matrix): "))

# create a matrix filled with zeros
# np.zeros((size,size)) creates a matrix with all elements = 0
matrix = np.zeros((size, size), dtype=int)

# set the first row to 1
matrix[0, :] = 1

# set the last row to 1
matrix[-1, :] = 1

# set the first column to 1
matrix[:, 0] = 1

# set the last column to 1
matrix[:, -1] = 1

# print the matrix
print("2D array with border 1 and inside 0:")
print(matrix)

Enter the size of the matrix (example 5 for a 5x5 matrix): 8
2D array with border 1 and inside 0:
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np  # import numpy library

# create an 8x8 matrix filled with zeros
# np.zeros((8,8)) creates a matrix with 8 rows and 8 columns
checkerboard = np.zeros((8,8), dtype=int)

# fill alternate positions with 1 to create checkerboard pattern
# [::2,1::2] selects even rows and odd columns
checkerboard[::2,1::2] = 1

# [1::2,::2] selects odd rows and even columns
checkerboard[1::2,::2] = 1

# print the checkerboard matrix
print("8x8 Checkerboard Pattern:")
print(checkerboard)

8x8 Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

1. Add the two array.

In [ ]:
import numpy as np  # import numpy library for array operations

# create array x
x = np.array([[1,2],[3,5]])  # 2x2 matrix

# create array y
y = np.array([[5,6],[7,8]])  # another 2x2 matrix

# add the two arrays
# numpy adds elements in the same position
result = x + y

# print arrays and result
print("Array x:")
print(x)

print("Array y:")
print(y)

print("Addition of x and y:")
print(result)

Array x:
[[1 2]
 [3 5]]
Array y:
[[5 6]
 [7 8]]
Addition of x and y:
[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np  # import numpy library for array operations

# create array x
x = np.array([[1,2],[3,5]])  # 2x2 matrix

# create array y
y = np.array([[5,6],[7,8]])  # another 2x2 matrix

# subtract array y from array x
# subtraction happens element by element
result = x - y

# print arrays and result
print("Array x:")
print(x)

print("Array y:")
print(y)

print("Subtraction of x - y:")
print(result)

Array x:
[[1 2]
 [3 5]]
Array y:
[[5 6]
 [7 8]]
Subtraction of x - y:
[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np  # import numpy library for array operations

# create array x
x = np.array([[1,2],[3,5]])  # 2x2 matrix

# ask the user to enter an integer for multiplication
num = int(input("Enter an integer to multiply the array: "))  # convert input to integer

# multiply the array with the integer
# each element of the array will be multiplied by the number
result = x * num

# print the original array
print("Original Array x:")
print(x)

# print the multiplication result
print("Array after multiplication:")
print(result)

Enter an integer to multiply the array: 5
Original Array x:
[[1 2]
 [3 5]]
Array after multiplication:
[[ 5 10]
 [15 25]]


4. Find the square of each element of the array.

In [ ]:
import numpy as np  # import numpy library for array operations

# create array x
x = np.array([[1,2],[3,5]])  # 2x2 matrix

# square each element of the array
# x**2 means every element is multiplied by itself
squared_array = x ** 2

# print the original array
print("Original Array x:")
print(x)

# print the squared array
print("Square of each element:")
print(squared_array)

Original Array x:
[[1 2]
 [3 5]]
Square of each element:
[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np  # import numpy library

# define the arrays
x = np.array([[1,2],[3,5]])  # 2x2 matrix
y = np.array([[5,6],[7,8]])  # another 2x2 matrix

v = np.array([9,10])  # vector
w = np.array([11,12]) # vector

# dot product between v and w
dot_vw = np.dot(v, w)  # multiplies corresponding elements and adds them

# dot product between x and v
dot_xv = np.dot(x, v)  # matrix-vector multiplication

# dot product between x and y
dot_xy = np.dot(x, y)  # matrix multiplication

# print results
print("Dot product of v and w:")
print(dot_vw)

print("Dot product of x and v:")
print(dot_xv)

print("Dot product of x and y:")
print(dot_xy)

Dot product of v and w:
219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np  # import numpy library

# define the arrays
x = np.array([[1,2],[3,5]])  # 2x2 matrix
y = np.array([[5,6],[7,8]])  # another 2x2 matrix

v = np.array([9,10])  # vector
w = np.array([11,12]) # vector

# concatenate x and y along rows
# axis = 0 means join vertically (row-wise)
concat_rows = np.concatenate((x, y), axis=0)

# concatenate v and w along columns
# first reshape them to column vectors
v_col = v.reshape(-1,1)  # convert v into a column vector
w_col = w.reshape(-1,1)  # convert w into a column vector

# concatenate column-wise
# axis = 1 means join horizontally (column-wise)
concat_cols = np.concatenate((v_col, w_col), axis=1)

# print results
print("Concatenation of x and y along rows:")
print(concat_rows)

print("Concatenation of v and w along columns:")
print(concat_cols)

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np  # import numpy library

# define the arrays
x = np.array([[1,2],[3,5]])  # 2x2 matrix
v = np.array([9,10])         # 1D vector

# print arrays first
print("Array x:")
print(x)

print("Array v:")
print(v)

# try to concatenate x and v
# this will produce an error because the dimensions are different
try:
    result = np.concatenate((x, v), axis=0)  # attempting concatenation
    print("Concatenated array:")
    print(result)

except ValueError as e:
    # catch the error and print explanation
    print("Error occurred:", e)

Array x:
[[1 2]
 [3 5]]
Array v:
[ 9 10]
Error occurred: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.


In [ ]:
import numpy as np  # import numpy library for matrix operations

# define matrix A
A = np.array([[3,4],[7,8]])  # 2x2 matrix

# print matrix A
print("Matrix A:")
print(A)

# calculate the inverse of matrix A
# np.linalg.inv() finds the inverse of a square matrix
A_inverse = np.linalg.inv(A)

# print the inverse of A
print("Inverse of A:")
print(A_inverse)

# multiply A with its inverse
# np.dot() performs matrix multiplication
result = np.dot(A, A_inverse)

# print the result
print("Result of A * A_inverse:")
print(result)

# create identity matrix of size 2x2 for comparison
I = np.eye(2)  # identity matrix

print("Identity Matrix I:")
print(I)

Matrix A:
[[3 4]
 [7 8]]
Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]
Result of A * A_inverse:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix I:
[[1. 0.]
 [0. 1.]]


2. Prove AB ̸= BA.

In [ ]:
import numpy as np  # import numpy library for matrix operations

# define matrix A
A = np.array([[3,4],[7,8]])  # 2x2 matrix

# define matrix B
B = np.array([[5,3],[2,1]])  # another 2x2 matrix

# print matrices
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

# calculate AB (A multiplied by B)
AB = np.dot(A, B)  # matrix multiplication

# calculate BA (B multiplied by A)
BA = np.dot(B, A)  # matrix multiplication

# print results
print("Matrix multiplication A * B:")
print(AB)

print("Matrix multiplication B * A:")
print(BA)

# check if they are equal
print("Are AB and BA equal?")
print(np.array_equal(AB, BA))  # returns False if matrices are different

Matrix A:
[[3 4]
 [7 8]]
Matrix B:
[[5 3]
 [2 1]]
Matrix multiplication A * B:
[[23 13]
 [51 29]]
Matrix multiplication B * A:
[[36 44]
 [13 16]]
Are AB and BA equal?
False


3. Prove (AB)T = BTAT

In [ ]:
import numpy as np  # import numpy library for matrix operations

# define matrices
A = np.array([[3,4],[7,8]])  # matrix A
B = np.array([[5,3],[2,1]])  # matrix B

# print matrices
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

# compute AB
AB = np.dot(A, B)  # matrix multiplication

# transpose of AB
AB_T = AB.T  # .T gives transpose of a matrix

# transpose of A and B
A_T = A.T
B_T = B.T

# compute B^T * A^T
BT_AT = np.dot(B_T, A_T)

# print results
print("Transpose of (AB):")
print(AB_T)

print("B^T * A^T:")
print(BT_AT)

# check if they are equal
print("Are they equal?")
print(np.array_equal(AB_T, BT_AT))

Matrix A:
[[3 4]
 [7 8]]
Matrix B:
[[5 3]
 [2 1]]
Transpose of (AB):
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Are they equal?
True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


In [ ]:
import numpy as np  # import numpy library for matrix operations

# create matrix A using coefficients of x, y, and z from the equations
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3,  1, -1]
])

# create matrix B using the constants from the right side of the equations
B = np.array([
    [-1],
    [-3],
    [9]
])

# print matrix A
print("Matrix A:")
print(A)

# print matrix B
print("Matrix B:")
print(B)

# find the inverse of matrix A
# np.linalg.inv(A) computes A inverse
A_inverse = np.linalg.inv(A)

# print inverse of A
print("Inverse of A:")
print(A_inverse)

# solve for X using the inverse formula:
# X = A^(-1) * B
X = np.dot(A_inverse, B)

# print the solution matrix X
print("Solution Matrix X:")
print(X)

# print values of x, y, and z separately for easy understanding
print("Value of x =", X[0][0])
print("Value of y =", X[1][0])
print("Value of z =", X[2][0])

Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Matrix B:
[[-1]
 [-3]
 [ 9]]
Inverse of A:
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution Matrix X:
[[ 2.]
 [ 1.]
 [-2.]]
Value of x = 2.0
Value of y = 1.0
Value of z = -2.0
